name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/gh-pages.yml'
      - 'public/**'
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build static site
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build script, skip."
          fi
      - name: Copy README.md to public
        run: |
          mkdir -p public
          cp README.md public/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
